"""
Models for the reports app.
Defines ReportLog to track generated reports.
"""
from django.db import models
from django.conf import settings

from core.models import BaseModel


class ReportLog(BaseModel):
    """
    Audit record for every report generated by a user.
    Tracks who generated what, with which filters, and how many records were returned.

    Inherits created_at, updated_at, is_active from BaseModel.
    """

    REPORT_TYPE_CHOICES = [
        ('clients', 'Clientes'),
        ('opportunities', 'Oportunidades'),
        ('followups', 'Seguimientos'),
        ('sales', 'Ventas Cerradas'),
    ]

    FORMAT_CHOICES = [
        ('pdf', 'PDF'),
        ('excel', 'Excel'),
        ('csv', 'CSV'),
        ('preview', 'Vista Previa'),
    ]

    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name='generated_reports',
        verbose_name='Generado por',
    )
    report_type = models.CharField(
        max_length=20,
        choices=REPORT_TYPE_CHOICES,
        verbose_name='Tipo de reporte',
    )
    export_format = models.CharField(
        max_length=10,
        choices=FORMAT_CHOICES,
        default='preview',
        verbose_name='Formato',
    )
    filters_applied = models.JSONField(
        default=dict,
        blank=True,
        verbose_name='Filtros aplicados',
    )
    record_count = models.PositiveIntegerField(
        default=0,
        verbose_name='Registros exportados',
    )
    generated_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Fecha de generación',
    )

    class Meta:
        verbose_name = 'Registro de reporte'
        verbose_name_plural = 'Registros de reportes'
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['generated_by', 'generated_at']),
            models.Index(fields=['report_type', 'export_format']),
        ]

    def __str__(self):
        return (
            f"{self.get_report_type_display()} — "
            f"{self.get_export_format_display()} — "
            f"{self.generated_at.strftime('%Y-%m-%d %H:%M')}"
        )
