# Generated by Django 6.0.5 on 2026-05-13 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_type', models.CharField(choices=[('clients', 'Clientes'), ('opportunities', 'Oportunidades'), ('followups', 'Seguimientos'), ('sales', 'Ventas Cerradas')], max_length=20, verbose_name='Tipo de reporte')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('preview', 'Vista Previa')], default='preview', max_length=10, verbose_name='Formato')),
                ('filters_applied', models.JSONField(blank=True, default=dict, verbose_name='Filtros aplicados')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='Registros exportados')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Registro de reporte',
                'verbose_name_plural': 'Registros de reportes',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['generated_by', 'generated_at'], name='reports_rep_generat_4c98d0_idx'), models.Index(fields=['report_type', 'export_format'], name='reports_rep_report__9fb57f_idx')],
            },
        ),
    ]
