# Generated by Django 6.0.3 on 2026-05-13 00:46

import clientes.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Empresa')),
                ('contact_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre de contacto')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[clientes.models._email_format_validator], verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, validators=[clientes.models._phone_format_validator], verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industria')),
                ('assigned_vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor asignado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.BooleanField(help_text='True = activo, False = inactivo', verbose_name='Estado anterior')),
                ('new_status', models.BooleanField(help_text='True = activo, False = inactivo', verbose_name='Nuevo estado')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='clientes.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['assigned_vendedor', 'is_active'], name='clientes_cl_assigne_c0ec02_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='clientes_cl_company_7092de_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='clientes_cl_email_7b5834_idx'),
        ),
    ]
