# Generated by Django 6.0.5 on 2026-05-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Correo destinatario')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=10, verbose_name='Estado')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registros de correo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('link', models.URLField(blank=True, verbose_name='Enlace')),
                ('notification_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('follow_up', 'Seguimiento'), ('stage_change', 'Cambio de etapa'), ('inactivity', 'Inactividad'), ('system', 'Sistema')], default='system', max_length=30, verbose_name='Tipo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
